export const companiesRows = [
  {
    id: 1,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Bridge to Business Company for exporting food products",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 2,
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 3,
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 4,
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 5,
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 6,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 7,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 8,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 9,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 10,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 11,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 12,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 13,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 14,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
  {
    id: 15,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Facebook",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    location: "London",
    employees: 200,
    address: "USA",
    branches: {
      brancheOne: "one",
      brancheTwo: "two",
      brancheThree: "three",
    },
  },
];

export const usersRows = [
  {
    id: 1,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "Online",
    verified: true,
  },
  {
    id: 2,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "Online",
    verified: true,
  },
  {
    id: 3,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "Online",
    verified: false,
  },
  {
    id: 4,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "offline",
    verified: true,
  },
  {
    id: 5,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "offline",
    verified: false,
  },
  {
    id: 6,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "busy",
    verified: true,
  },
  {
    id: 7,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Ahmed Moamed",
    email: "ahmed20@gmail.com",
    phone: "0123456789",
    location: "London",
    employees: 200,
    address: "USA",
    username: "ahmed20",
    lastlogin: "Wed-09-2023 at 9:30pm",
    status: "busy",
    verified: false,
  },
];

export const teamsRows = [
  {
    id: 1,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Bridge to Business Company for exporting food products",
    field: "Marketing",
    location: "London",
    employees: 10,
    branche: "Cairo",
  },
  {
    id: 2,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Bridge to Business Company for exporting food products",
    field: "Marketing",
    location: "London",
    employees: 10,
    branche: "Cairo",
  },
  {
    id: 3,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Bridge to Business Company for exporting food products",
    field: "Marketing",
    location: "London",
    employees: 10,
    branche: "Cairo",
  },
  {
    id: 4,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Bridge to Business Company for exporting food products",
    field: "Marketing",
    location: "London",
    employees: 10,
    branche: "Cairo",
  },
  {
    id: 5,
    photo:
      "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Bridge to Business Company for exporting food products",
    field: "Marketing",
    location: "London",
    employees: 10,
    branche: "Cairo",
  },
];
